on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: git checkout
      run: git checkout main      

    - name: install python packages
      run: python -m pip install py7zr xmltodict

    - name: extract.py
      run: python extract.py
    
    - name: git config
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: git add
      run: git add ${{ github.workspace }}\pages\
    
    - name: git commit
      run: git commit -m "解包"
        
    - name: git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
